navikt/veilarbvedtaksstotte

src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java
src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java

Tilsvarende logikk som for versjon 1: sett evt tidligere gjeldende vedtak til historisk, slett bruker fra beslutteroversikt, og send status endring.

Legg til logikk for ferdigstilling av vedtak v2

---

src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java
src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java

Legg til sender-lås funksjonalitet for fatt vedtak v2 for å redusere risiko for å sende duplikate dokument. Skrive om test av funksjonalitet i forsøk på å gjøre testen mer stabil.

Legg til sender-lås for fatt vedtak v2

---

src/main/java/no/nav/veilarbvedtaksstotte/controller/InnsatsbehovController.kt
src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java
src/main/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovService.kt
src/main/java/no/nav/veilarbvedtaksstotte/utils/OppfolgingUtils.java
src/test/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepositoryTest.java
src/test/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovServiceTest.kt
src/test/java/no/nav/veilarbvedtaksstotte/utils/OppfolgingUtilsTest.java

Tar bort logikk for gjeldende innsatsbehov basert på oppfølgingsperiode. Logikk endret til å returnere innsatsbehov fra siste vedtak enten fra ny løsning eller Arena.

Forenkler logikk for innsatsbehov

---

src/main/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovService.kt
src/test/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovServiceTest.kt

Sammenligner om Kafka-melding fra Arena er den siste basert på hendelseId i stede for equality-sjekk på hele ArenaVedtak-objektet.

Forenkler sjekk for om innsatsbehov fra Arena skal publiseres på Kafka

---

nais-dev.yaml
nais-prod.yaml
src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConfig.java
src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaProperties.java
src/main/resources/application-local.properties
src/main/resources/application.properties

Fortsetter produsering on prem i deploy-vindu, slik at det ikke ligger igjen uprosesserte meldinger i kafka_producer_record-tabellen for on prem topic.

Produser innsatsbehov på Kafka on prem og Aiven

---

src/main/java/no/nav/veilarbvedtaksstotte/domain/vedtak/ArenaVedtak.kt
src/main/java/no/nav/veilarbvedtaksstotte/service/ArenaVedtakService.java
src/test/java/no/nav/veilarbvedtaksstotte/service/ArenaVedtakServiceTest.java
src/test/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakServiceTest.kt

Bruker kun hendelse id for å avgjøre om et vedtak fra Arena er nyere enn et annet vedtak fra Arena. Tidligere logikk med beregnet fattet tidspunkt kan bli feil dersom meldinger sendes på nytt slik at det ikke er mulig å beregne fattet tidspunkt (blir da kl. 00:00).

Fikser og forenkler logikk for behandling av Arena vedtak

---

src/main/java/no/nav/veilarbvedtaksstotte/domain/DistribusjonBestillingId.kt
src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java
src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java

Dette for å tilrettelegge støtte for ny dok.integrasjon med asynkron distribusjon av vedtak basert på fattede vedtak som mangler dokument_bestilling_id.

Lagrer - på dokument_bestilling_id for gammel dok.integrasjon

---

src/main/java/no/nav/veilarbvedtaksstotte/client/dokdistfordeling/DokdistribusjonClientImpl.kt
src/test/java/no/nav/veilarbvedtaksstotte/service/DistribusjonServiceTest.kt

Dersom vedtaket allerede er distribuert så svarer dokdist med status 409 CONFLICT og returnerer bestillingsId i respons.
Co-authored-by: Mathias S. Müller <mathias.sundt.muller@nav.no>

Håndter statuskode 409 CONFLICT fra dokdist og lagre bestillingsId i respons

---

src/main/java/no/nav/veilarbvedtaksstotte/client/dokarkiv/DokarkivClientImpl.kt
src/main/java/no/nav/veilarbvedtaksstotte/client/dokdistfordeling/DokdistribusjonClientImpl.kt
src/test/java/no/nav/veilarbvedtaksstotte/service/DokumentServiceTest.kt

Dersom vedtaket allerede er journalført så svarer dokarkiv med status 409 CONFLICT og returnerer samme responsobjekt som ved 201 CREATED.

Håndterer statuskode 409 CONFLICT fra dokarkiv

---

src/main/java/no/nav/veilarbvedtaksstotte/domain/kafka/KafkaVedtakStatusEndring.java
src/main/java/no/nav/veilarbvedtaksstotte/service/BeslutterService.java
src/main/java/no/nav/veilarbvedtaksstotte/service/DvhRapporteringService.kt
src/main/java/no/nav/veilarbvedtaksstotte/service/MetricsService.java
src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakHendelserService.java
src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java
src/test/java/no/nav/veilarbvedtaksstotte/config/ServiceTestConfig.java
src/test/java/no/nav/veilarbvedtaksstotte/service/BeslutterServiceTest.java
src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java

- Rename VedtakStatusEndringService til VedtakHendelserService
- Flytt ut metrikker fra VedtakHendelserService så den kun har ansvar for å sende Kafka-meldinger
- Flytter ut sending på Kafka-topic for DVH i egen service, DvhRapporteringService, for å tilrettelegge for å gjøre dette asynkront med bedre feilhåndtering

Refaktorer hva som skjer i VedtakStatusEndringService

---

src/main/java/no/nav/veilarbvedtaksstotte/metrics/DokumentdistribusjonMeterBinder.kt
src/test/java/no/nav/veilarbvedtaksstotte/metrics/DokumentdistribusjonMeterBinderTest.kt

Øker tid før et vedtak som er fattet blir talt med som ikke distribuert. For å unngå falsk alarm ved deploy av app.

Endrer metrikk for alarm

---

src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.java

Forrige "fiks" fungerte dårlig da vi plutselig fikk `saf-q1-q1` i ingressen. Håndterer dette i denne PR-en.

Spesifiser miljø i serviceName kun i dev for SAF-klient

---

src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.java

dokdistfordeling (som brukes for distribusjon av dokumenter) krever token med scope for saf. saf endret tidligere navn på app for scope fra saf til saf-q1

Fiks saf scope for dokdistfordeling

---

nais-dev.yaml
nais-prod.yaml
src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConsumerConfig.kt
src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java
src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerService.java
src/main/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakService.kt
src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java
src/test/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepositoryTest.java
src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerServiceTest.java
src/test/java/no/nav/veilarbvedtaksstotte/utils/AbstractVedtakIntegrationTest.kt

Endret fra onprem-topic aapen-fo-endringPaaAvsluttOppfolging-v1-q1 til Aiven topic pto.oppfolging-avsluttet-v1 i dev. Siden topicen ikke er idempotent måtte vi legge inn en datosjekk. Når vi leser alle meldingene på nytt, vil vi kun lese meldinger om oppfolging avsluttet. Dette vil kunne føre til at vi setter vedtak som er fattet etter oppf avsluttet til historiske. Vi må derfor sjekke datoen vedtaket er fattet opp mot datoen for avslutt oppfolging, og kun sette vedtaket til historisk dersom det er fattet før oppf avsluttet.
Co-authored-by: Oda Dahlen <oda.dahlen@bekk.no>
Co-authored-by: Sondre Larsen Ovrid <sondre.larsen.ovrid@nav.no>

Prodsetting: Kafka pa aiven endring pa avslutt oppfolging (#356)

---

nais-prod.yaml

Ref. endring i default brukertilganger for AzureAD, som annonsert i #nais-announcements: https://nav-it.slack.com/archives/C01DE3M9YBV/p1674475818557619

Prodsette: TC-320 Gi alle AzureAD-brukere tilgang i prod (#375)

---

src/main/java/no/nav/veilarbvedtaksstotte/config/CustomWebMvcConfigurer.java
src/main/java/no/nav/veilarbvedtaksstotte/config/FnrUsageLoggerInterceptor.java

Legger til funksjonalitet for å sjekke og eventuelt logge en beskjed dersom vi har konsumenter som går mot endepunkter i applikasjonen som inneholder fnr-parametre (path-params eller query-params). Sjekken er veldig enkel/dum og ser bare på henholdsvis URIen og query-stringen og sjekker om de inneholder en sekvens av elleve siffer.
Bruker `HandlerInterceptor`-konseptet til dette formålet slik at vi kan sette opp sjekken _en_ plass. Registrerer `FnrUsageLoggerInterceptor` i `InterceptorRegistry`-et til Spring slik at requester til appen blir sendt gjennom sjekken gitt i `preHandle`-metoden (se forøvrig: [Spring MVC HandlerInterceptor vs Filter: Key differences and use-cases](https://www.baeldung.com/spring-mvc-handlerinterceptor-vs-filter#key-differences-and-use-cases)).
Tanken er å bruke …

Logg konsumenter som bruker fnr i path-/query-params

---

.github/workflows/build-push-deploy-dev.yml
.github/workflows/main.yml
.nais/application/application-config-dev.yaml
.nais/application/application-config-prod.yaml

Bytter fra `docker/build-push-action` GitHub action til å bruke NAIS sin `nais/docker-build-push` GitHub action. Dette gir oss en del fordeler blant annet mtp. stabilitet ved image-pulls da `nais/docker-build-push` går mot Google Artifact Registry (GAR) i stedet for GitHub Container Registry (GHCR), samt automatisk signering/scanning av Docker images via SALSA.
Det står en god del om dette i NAIS-docen, bla.a. [Salsa - NAIS](https://doc.nais.io/security/salsa/salsa) og [OCI registry migration - NAIS](https://doc.nais.io/guides/oci-migration/). Noen relevante utdrag:
> [SLSA](https://slsa.dev/) is short for Supply chain Levels for Software Artifacts pronounced salsa.
>
> It is a security framework, essentially a checklist comprising standards and controls aimed at preventing tampering, …

Bytt til "nais/docker-build-push"-action

---

.nais/application/application-config-prod.yaml

Ref: https://doc.nav.cloud.nais.io/reference/application-spec/#accesspolicyoutboundexternalhost

Fjern protokoll fra "host" da det ikke er tillatt

---

pom.xml

Ser ut som springdoc-swagger genereringen sluttet å virke når vi gikk over til Spring Boot 3.x.x. Med ny springdoc-komponent skal det fungere igjen, ref: https://stackoverflow.com/a/75789657.
Verifisert i dev.

Bytt til ny springdoc-komponent som støtter Spring Boot versjon 3.x.x

---

.nais/application/application-config-prod.yaml

Forrige forsøk hadde for få vCPUer (til tross for at vi ikke trenger mer enn 1 ...), det er maks 6,5 GB minne per vCPU.
⚠️ Må merges etter 16, siden det krever en restart av database-instansen

Bruk gyldige databaseressursverdier

---

.nais/application/application-config-dev.yaml
.nais/application/application-config-prod.yaml

For å rette feil i komets løsninger så trenger vi å hente gjeldende innsatsgruppe isteden for den siste
https://trello.com/c/s0YN7ag6/2202-vi-bruker-i-noen-tilfeller-feil-innsatsgruppe-for-p%C3%A5melding

Gir komet tilgang til endepunkt for å hende gjeldende 14a vedtak

---

pom.xml

Har forsøkt å ha høyere versjoner men det går ikke helt uten videre. Nedgraderer derfor pakkene akkurat for lanseringsdagen, men jobber videre for å finne en mer permanent løsning på problemet.

Nedgraderer logback-pakker slik at vi får tilbake x_-tagger i loggene for lanseringsdagen

---

src/main/java/no/nav/veilarbvedtaksstotte/client/person/VeilarbpersonClient.kt
src/main/java/no/nav/veilarbvedtaksstotte/client/person/VeilarbpersonClientImpl.kt
src/main/java/no/nav/veilarbvedtaksstotte/service/DokumentService.kt
src/test/java/no/nav/veilarbvedtaksstotte/config/ClientTestConfig.java
src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java

Når et vedtak fattes forsøker vi å journalføre det. Dersom det feiler ved journalføring så blir det plukket opp på et senere tidspunkt av en batch-jobb og forsøkt journalført på nytt.
Vi hadde en feil der slike vedtak (som var forsøkt journalført og ble plukket opp av jobben) _ikke_ kunne journalføres. Rotårsaken var at ifm. journalføring forsøker vi å hente brukers navn (`VeilarbpersonClient.hentPersonNavn`), men med user-token. Det funker dårlig i en batch-jobb kontekst.

Bruke machine-to-machine token for å hente navn ved journalføring

---

.nais/alerts/alerts-config-prod.yaml

Gjeldande batch-storleik: 100 meldingar.
Av ein eller annan grunn tel prometheus alle meldingane dobbelt, derav "> 100" for 50 meldingar og "> 200" for full kø.

Legg til alarm for når distribusjon vert blokkert  av for mange feilande poster i utsendingskøen
