navikt/veilarbvedtaksstotte

src/main/java/no/nav/fo/veilarbvedtaksstotte/domain/KafkaVedtakSendt.java, src/main/java/no/nav/fo/veilarbvedtaksstotte/domain/Vedtak.java, src/main/java/no/nav/fo/veilarbvedtaksstotte/repository/KafkaRepository.java, src/main/java/no/nav/fo/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java, src/main/java/no/nav/fo/veilarbvedtaksstotte/service/KafkaService.java, src/main/java/no/nav/fo/veilarbvedtaksstotte/service/VedtakService.java
Sist endret vil være tidspunktet for anårvedtaket er sendt. Bruke dette tidspunktet i kafka-melding for evt replay støtte.
=> FO-2162 bruk sist endret fra vedtak i kafka-melding

src/main/java/no/nav/veilarbvedtaksstotte/controller/BeslutterController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/MeldingController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/UtkastController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/VedtakController.java, src/main/java/no/nav/veilarbvedtaksstotte/domain/LagUtkastDTO.java, src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java, src/main/java/no/nav/veilarbvedtaksstotte/service/ArenaVedtakService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/BeslutterService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/MalTypeService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/MeldingService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/MetricsService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/OyeblikksbildeService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java, src/test/java/no/nav/veilarbvedtaksstotte/config/ControllerTestConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/BeslutteroversiktRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/KafkaRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/KilderRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/MeldingRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/OyeblikksbildeRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/BeslutterServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/utils/TestData.java
Fjernet bruk av fnr så mye som mulig og erstattet med vedtakId
=> FO-2959 Refaktorerte store deler av vedtak APIet.

pom.xml, src/test/java/no/nav/veilarbvedtaksstotte/client/registrering/VeilarbregistreringClientTest.java, src/test/resources/registrering.json
Deserialisering av LocalDateTime fra veilarbregistrering feilet pga mangldende håntering når offset på dato manglet. Dette er fikset ved bump av common.
=> Fiks for date deserialisering

src/main/java/no/nav/veilarbvedtaksstotte/kafka/dto/KafkaVedtakStatusEndring.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakStatusEndringService.java
Porteføljeoversikten trenger ansvarlig veileder for visning
=> Legg til felter for ansvarlig veileder på kafka når utkast opprettes

pom.xml
https://github.com/spring-projects/spring-boot/releases/tag/v2.4.3
=> Bump til versjon 2.4.3 av spring-boot som har fikset nimbus avhengigheter

src/main/java/no/nav/veilarbvedtaksstotte/client/dokarkiv/SafClient.java, src/main/java/no/nav/veilarbvedtaksstotte/client/dokarkiv/SafClientImpl.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/UtkastController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/VedtakController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/dto/LagUtkastDTO.java, src/main/java/no/nav/veilarbvedtaksstotte/service/ArenaVedtakService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/BeslutterService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovService.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/MeldingService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/OyeblikksbildeService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java, src/test/java/no/nav/veilarbvedtaksstotte/client/arena/VeilarbarenaClientImplTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/client/dokument/VeilarbdokumentClientImplTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/client/person/VeilarbpersonClientImplTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/client/registrering/VeilarbregistreringClientTest.java, src/test/java/no/nav/veilarbvedtaksstotte/client/veilarboppfolging/VeilarboppfolgingClientImplTest.java, src/test/java/no/nav/veilarbvedtaksstotte/config/ClientTestConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/BeslutteroversiktRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/AuthServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/BeslutterServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/utils/TestData.java
Refaktorer eksisterende tilgangssjekk for bruker og enhet, og legger til ny sjekk for kun bruker.
=> Tilgangssjekk på bruker men ikke enhet for /innsatsbehov API

src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaProducerService.java, src/test/java/no/nav/veilarbvedtaksstotte/kafka/InnsatsbehovKafkaProducerTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaProducerServiceTest.kt
Sletter ikke innsatsbehov på Kafka når oppfølging avsluttes. Henger sammen med 5a29461a325aec72e103d71b83c3a86928a35e3e
=> Sletter ikke innsatsbehov på Kafka

src/main/java/no/nav/veilarbvedtaksstotte/controller/AdminController.java, src/main/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepository.java, src/main/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovService.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaRepubliseringService.kt, src/test/java/no/nav/veilarbvedtaksstotte/config/ServiceTestConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/ArenaVedtakRepositoryTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/repository/BeslutterRepositorySokTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/BeslutteroversiktRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/KilderRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/MeldingRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/OyeblikksbildeRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/UtrullingRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/repository/VedtaksstotteRepositoryTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/ArenaVedtakServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/InnsatsbehovServiceTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaRepubliseringServiceTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/utils/DatabaseTest.kt
Admin API for republisering av innsatsbehov for brukere som har fått vedtak i vedtaksstøtte (ny/denne løsningen).
=> Admin API for republisering av innsatsbehov

src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VeilederService.java, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceValiderVedtakForFerdigstillingOgUtsendingTest.java
Burde håndtere at vedtaksstøtte vises hvis en veileder som har fattet et vedtak blir inaktiv
=> Legg til feilhåndtering på setting av veiledernavn

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaProperties.java, src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaProducerService.java, src/main/resources/application-local.properties, src/main/resources/application.properties, src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaProducerServiceTest.kt
=> Tar bort topic for vedtak statusendring on-prem

src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/config/EnvironmentProperties.java, src/main/java/no/nav/veilarbvedtaksstotte/service/UnleashService.java, src/main/resources/application.properties, src/test/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakServiceTest.kt
Bruker kun nå kun PDL. Endret også til å gå mot pdl i q1 i stede for dev (q2).
=> Saner bruk av aktørregisteret

src/main/java/no/nav/veilarbvedtaksstotte/client/dokdistfordeling/DistribuerJournalpostDTO.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/DistribusjonServiceV2.kt, src/test/java/no/nav/veilarbvedtaksstotte/client/dokdistfordeling/DokdistribusjonClientTest.kt
=> Legg til nye felter i kall til dokdist

src/main/java/no/nav/veilarbvedtaksstotte/service/UnleashService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakService.java, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java
Default er nå ny integrasjon slik at gammel ikke brukes dersom Unleash er utilgjengelig.
=> Snu om på toggle for ny dokintegrasjon

src/main/java/no/nav/veilarbvedtaksstotte/client/arena/UserTokenProviderVeilarbveileder.java, src/main/java/no/nav/veilarbvedtaksstotte/client/veilederogenhet/VeilarbveilederClientImpl.java, src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.java, src/test/java/no/nav/veilarbvedtaksstotte/client/veilederogenhet/VeilarbveilederClientImplTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/config/ApplicationTestConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/service/DokumentServiceTest.kt
Legger til Bearer for alle obo tokens
=> Obo for veilarbveileder

.github/workflows/main.yml, nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbvedtaksstotte/config/FilterConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/AdminController.java, src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.java
=> Prodsetting: pto-admin AzureAd

pom.xml, src/main/java/no/nav/veilarbvedtaksstotte/client/DownstreamAPIs.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/dokarkiv/DokarkivClientImpl.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/regoppslag/RegoppslagClientImpl.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/ApplicationConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/client/regoppslag/RegoppslagClientTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/DokumentServiceTest.kt
=> Regoppslag med AzureAd

src/main/java/no/nav/veilarbvedtaksstotte/service/DvhRapporteringService.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaVedtakStatusEndringConsumer.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/UnleashService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/VedtakHendelserService.java, src/test/java/no/nav/veilarbvedtaksstotte/kafka/KafkaVedtakStatusEndringConsumerTest.kt
=> Fjerner toggles for overføring til DVH

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbvedtaksstotte/controller/AdminController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/Siste14aVedtakController.kt, src/main/java/no/nav/veilarbvedtaksstotte/controller/dto/Siste14aVedtakDTO.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakService.kt, src/test/java/no/nav/veilarbvedtaksstotte/controller/MeldingControllerTest.java, src/test/java/no/nav/veilarbvedtaksstotte/controller/Siste14aVedtakControllerTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/AuthServiceTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakServiceTest.kt
Legg til resterende felter (bortsett fra aktorId) slik at det samsvarer med Kafka-meldinger
=> Utvid siste 14a API

src/main/java/no/nav/veilarbvedtaksstotte/client/DownstreamAPIs.kt
Ref: https://nav-it.slack.com/archives/CDBKYSE7Q/p1668165420362299
=> Oppdatere til nytt SAF-scope i dev

src/main/java/no/nav/veilarbvedtaksstotte/domain/kafka/KafkaOppfolgingsbrukerEndringV2.java, src/main/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerService.java, src/main/java/no/nav/veilarbvedtaksstotte/service/Siste14aVedtakService.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/KafkaConsumerServiceTest.java
Det feiler pga vi får data fra Arena q1 som er prodlike (vaska), men vi støtter kun helsyntetiske data
=> La til sjekk på om vi er i dev ved henting av AktorId-oppslag

src/main/java/no/nav/veilarbvedtaksstotte/client/dokarkiv/SafClientImpl.java
Har testet manuelt med nytt endepunkt.
=> TC-318 Bytt endepunkt for helsesjekk mot SAF

pom.xml, src/main/java/no/nav/veilarbvedtaksstotte/config/ApplicationConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/DatabaseConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/config/EnvironmentProperties.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConsumerConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaProperties.kt, src/main/resources/application-local.properties, src/main/resources/application.properties, src/test/java/no/nav/veilarbvedtaksstotte/config/ApplicationTestConfig.kt, src/test/java/no/nav/veilarbvedtaksstotte/mock/PepMock.java
This reverts commit b951abb450415e3744921272219f739ee887ec7c, reversing changes made to fdcb52c9715e6b67abd0c6936380ada70ae46b4f.
=> Revert "Merge pull request #386 from navikt/Tc-336_Spring_Boot_3"

pom.xml, src/main/java/no/nav/veilarbvedtaksstotte/config/ApplicationConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/DatabaseConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/config/EnvironmentProperties.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConsumerConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaProperties.kt, src/main/resources/application-local.properties, src/main/resources/application.properties, src/test/java/no/nav/veilarbvedtaksstotte/config/ApplicationTestConfig.kt, src/test/java/no/nav/veilarbvedtaksstotte/mock/PepMock.java
Commit-meldingen ble litt rar av den grunn at jeg reverter en revertet endring. I praksis så betyr det at denne PR-en tar inn de samme endringene ifm. Spring Boot 3 som jeg opprinnelig hadde merget inn.
Kan sammenlignes om ønskelig med [den opprinnelige PR-en](https://github.com/navikt/veilarbvedtaksstotte/pull/387/files).
=> Spring Boot 3

src/main/java/no/nav/veilarbvedtaksstotte/config/KafkaConsumerConfig.kt
Vi har informert pilotkontoret og kan derfor starte konsumering fra ny topic.
=> TC-353 Start konsumering fra pto.siste-oppfolgingsperiode-v1

.github/workflows/build-push-deploy-dev.yml, .github/workflows/deploy-alerts-to-prod.yaml, pom.xml, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/AiaBackendClient.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/AiaBackendClientImpl.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/EgenvurderingData.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/EgenvurderingForPersonDTO.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/EgenvurderingResponseDTO.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/EndringIRegistreringdataRequest.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/EndringIRegistreringsdataResponse.kt, src/main/java/no/nav/veilarbvedtaksstotte/client/egenvurdering/EgenvurderingClient.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/ClientConfig.kt, src/main/java/no/nav/veilarbvedtaksstotte/config/HealthConfig.java, src/main/java/no/nav/veilarbvedtaksstotte/service/OyeblikksbildeService.java, src/test/java/no/nav/veilarbvedtaksstotte/client/aiaBackend/AiaBackendClientTest.java, src/test/java/no/nav/veilarbvedtaksstotte/config/ClientTestConfig.java, src/test/java/no/nav/veilarbvedtaksstotte/service/OyeblikksbildeServiceTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/VedtakServiceTest.java
* Byttet navn på client til aiaBackend istedenfor at den heter egenvurderingClient
* Litt usikker på om det er best å løse oppdateringen av registreringsdataen på denne måten: Gå igjennom JSONstringen, men hva tror dere?
=> Oppdatering av registreringsdata for øyblikksbilde dersom bruker har endret 'Din situasjon'

.nais/application/application-config-dev.yaml, .nais/application/application-config-prod.yaml, src/main/java/no/nav/veilarbvedtaksstotte/utils/DbUtils.java
Reverts navikt/veilarbvedtaksstotte#486
=> Revert "Migrate to ny Postres instances"

src/main/java/no/nav/veilarbvedtaksstotte/client/person/VeilarbpersonClientImpl.kt
Endrer tilbake fra maskintoken til userToken på hent-navn
=> FS-329724 Kan ikke starte beslutterprosess

.nais/application/application-config-dev.yaml
Reverts navikt/veilarbvedtaksstotte#545
=> Revert "Update application-config-dev.yaml"

src/main/java/no/nav/veilarbvedtaksstotte/service/AuthService.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/BeslutteroversiktService.java
* Fix tilgang for beslutter oversikt
=> Beslutter oversikt fix (#556)

.nais/application/application-config-dev.yaml, .nais/application/application-config-prod.yaml
Reverts navikt/veilarbvedtaksstotte#571
=> Revert "Veilarbportefolje tilgang"

.github/workflows/gcp/build-push-deploy-dev.yml, .github/workflows/gcp/codeql.yml, .github/workflows/gcp/deploy-alerts-to-prod.yaml, .github/workflows/gcp/deploy-unleash-apitoken.yaml, .github/workflows/gcp/main.yml, .nais/application/gcp/application-config-dev.yaml, .nais/application/gcp/application-config-prod.yaml, .nais/application/gcp/unleash-apitoken-dev.yaml, .nais/application/gcp/unleash-apitoken-prod.yaml
=> Add workflows for gcp

src/main/java/no/nav/veilarbvedtaksstotte/controller/v2/KodeverkV2Controller.kt, src/main/java/no/nav/veilarbvedtaksstotte/controller/v2/dto/KodeverkV2DTO.kt, src/main/java/no/nav/veilarbvedtaksstotte/domain/vedtak/InnsatsgruppeDetaljertV2.kt
=> Forslag kodeverksendepunkt for team Oppfølging

src/main/java/no/nav/veilarbvedtaksstotte/controller/BeslutterController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/MeldingController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/UtkastController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/VedtakController.java, src/main/java/no/nav/veilarbvedtaksstotte/controller/v2/UtkastV2Controller.kt, src/main/java/no/nav/veilarbvedtaksstotte/controller/v2/VedtakV2Controller.kt, src/main/java/no/nav/veilarbvedtaksstotte/service/UtrullingService.java, src/main/java/no/nav/veilarbvedtaksstotte/utils/UnleashUtils.kt, src/test/java/no/nav/veilarbvedtaksstotte/controller/v2/UtkastV2ControllerTest.kt, src/test/java/no/nav/veilarbvedtaksstotte/service/UtrullingServiceTest.kt
- Lag felles-funksjon som kan sjekke begge feature-togglar (unleash + kontortoggle)
- Legg til sjekk mot unleash-toggle
Trello-kort: https://trello.com/c/QVzpXFsr/898-gjere-at-ein-kan-toggle-p%C3%A5-vedtaksl%C3%B8sningen-for-enkeltveileder
=> Ta i bruk feature-toggle frå Unleash til å styre tilgang til endepunkt

src/main/java/no/nav/veilarbvedtaksstotte/controller/Gjeldende14aVedtakController.kt, src/test/java/no/nav/veilarbvedtaksstotte/controller/Gjeldende14avedtakControllerTest.kt
slik at det går raskare å finne info på det neste gong (og for konsumentar)
=> Legg til test og dokumentasjon på "person utan vedtak returnerer null"
